{% set version = "20171231" %}

package:
  name: lastools
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/gillins/LAStools/archive/{{ version }}.tar.gz
  sha256: b9b3d6fb556735b6cf751e9383669f843fa501ab755b6552f8cec2fccea417d5

build:
  number: 1001

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

  run:

test:
  commands:
    - if not exist %LIBRARY_BIN%\\las.dll exit 1        # [win]
    - if not exist %LIBRARY_LIB%\\las.lib exit 1        # [win]
    - if not exist %LIBRARY_INC%\\lasreader.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\\laswriter.hpp exit 1  # [win]
    - test -f $PREFIX/lib/liblas.so                     # [linux]
    - test -f $PREFIX/lib/liblas.dylib                  # [osx]
    - test -f $PREFIX/include/lasreader.hpp             # [unix]
    - test -f $PREFIX/include/laswriter.hpp             # [unix]
    - lasdiff -h
    - las2txt -h
    - lasindex -h
    - lasmerge -h
    - txt2las -h
    - lasprecision -h
    - las2las -h
    - laszip -h
    - lasinfo -h

about:
  home: http://www.cs.unc.edu/~isenburg/lastools/
  license: LGPL-2.1-only
  license_file: LICENSE.txt
  summary: LASlib and LASzip libraries plus open source utilities from LAStools for manipulating LiDAR data in LAS format

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - armstonj
